# Generated by Django 5.0.7 on 2024-07-27 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_assessment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskassessment',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='riskassessment',
            name='created_at',
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='impact',
            field=models.TextField(default='Default Impact'),
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='recommendations',
            field=models.TextField(default='Default Recommendations'),
        ),
        migrations.AlterField(
            model_name='riskassessment',
            name='assets',
            field=models.TextField(default='Default Assets'),
        ),
        migrations.AlterField(
            model_name='riskassessment',
            name='controls',
            field=models.TextField(default='Default Controls'),
        ),
        migrations.AlterField(
            model_name='riskassessment',
            name='potential_impact',
            field=models.TextField(default='Default Potential Impact'),
        ),
        migrations.AlterField(
            model_name='riskassessment',
            name='recommended_treatments',
            field=models.TextField(default='Default Recommended Treatments'),
        ),
        migrations.AlterField(
            model_name='riskassessment',
            name='risk_drivers',
            field=models.TextField(default='Default Risk Drivers'),
        ),
        migrations.AlterField(
            model_name='riskassessment',
            name='risk_level',
            field=models.CharField(default='Low', max_length=100),
        ),
        migrations.AlterField(
            model_name='riskassessment',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
