# Generated by Django 5.0.7 on 2024-07-29 00:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_assessment', '0002_alter_riskassessment_created_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Control',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('effectiveness', models.CharField(choices=[('very_effective', 'Very Effective'), ('effective', 'Effective'), ('somewhat_effective', 'Somewhat Effective'), ('ineffective', 'Ineffective')], max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='riskassessment',
            name='assets',
        ),
        migrations.RemoveField(
            model_name='riskassessment',
            name='controls',
        ),
        migrations.RemoveField(
            model_name='riskassessment',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='riskassessment',
            name='description',
        ),
        migrations.RemoveField(
            model_name='riskassessment',
            name='impact',
        ),
        migrations.RemoveField(
            model_name='riskassessment',
            name='potential_impact',
        ),
        migrations.RemoveField(
            model_name='riskassessment',
            name='recommendations',
        ),
        migrations.RemoveField(
            model_name='riskassessment',
            name='recommended_treatments',
        ),
        migrations.RemoveField(
            model_name='riskassessment',
            name='risk_drivers',
        ),
        migrations.RemoveField(
            model_name='riskassessment',
            name='risk_level',
        ),
        migrations.RemoveField(
            model_name='riskassessment',
            name='title',
        ),
        migrations.RemoveField(
            model_name='riskassessment',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='field1',
            field=models.CharField(default='default_value1', max_length=100),
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='field2',
            field=models.CharField(default='default_value2', max_length=100),
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='field3',
            field=models.CharField(default='default_value3', max_length=100),
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='field4',
            field=models.CharField(default='default_value4', max_length=100),
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='field5',
            field=models.CharField(default='default_value5', max_length=100),
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='field6',
            field=models.CharField(default='default_value6', max_length=100),
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='field7',
            field=models.CharField(default='default_value7', max_length=100),
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='field8',
            field=models.CharField(default='default_value8', max_length=100),
        ),
        migrations.CreateModel(
            name='AssessmentControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risk_assessment.riskassessment')),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risk_assessment.control')),
            ],
        ),
    ]
